import {
  faBan,
  faBars,
  faBox,
  faChampagneGlasses,
  faChessRook,
  faCircle,
  faCircleNotch,
  faDollarSign,
  faEarthEurope,
  faExclamation,
  faEye,
  faFire,
  faHillRockslide, faHouse, faKitchenSet, faLightbulb, faMinus, faMugSaucer, faPersonSkiing, faPlus, faSailboat,
  faSearch, faSnowflake, faTent, faTowerObservation, faTractor, faTrashCan, faTree, faUmbrellaBeach,
  faUser, faWater,
  IconDefinition
} from "@fortawesome/free-solid-svg-icons";
import {faAirbnb} from "@fortawesome/free-brands-svg-icons";

export const fontAwesomeIcons: IconDefinition[] = [
  faBan,
  faBars,
  faBox,
  faChampagneGlasses,
  faChessRook,
  faCircle,
  faCircleNotch,
  faDollarSign,
  faEarthEurope,
  faExclamation,
  faEye,
  faFire,
  faHillRockslide,
  faHouse,
  faKitchenSet,
  faLightbulb,
  faMinus,
  faMugSaucer,
  faPersonSkiing,
  faPlus,
  faSailboat,
  faSearch,
  faSnowflake,
  faTent,
  faTowerObservation,
  faTractor,
  faTrashCan,
  faTree,
  faUmbrellaBeach,
  faUser,
  faWater,
  faAirbnb
]
